### PR TITLE
Json schema feature/version/0.9.0

### PR DESCRIPTION
**Pull request by pbelmann**
Solves isues #3, #6, #8 and #4

### CODE REVIEW

**Comment by michaelbarton** [comment]
I gave this a try, and created the branch 'feature/tidy-feature-tests'. I added 'script/test' to the run the validator using soap. I however got two failing scenarios.

**Comment by pbelmann** [comment]
@michaelbarton 
I updated your feature/tidy-feature-tests branch and it works locally. But on circle ci there appears an error :

http:///var/run/docker.sock/v1.17/build?dockerfile=Dockerfile&rm=1&t=soap: dial unix /var/run/docker.sock: no such file or directory"

This sometimes happens on my local machine too. It seems to be docker bug.

**Comment by pbelmann** [comment]
I will open an issue for this error since we have to fix this somehow.

**Comment by pbelmann** [comment]
ok i fixed the docker issue with the newest wrapdocker file but there seem to be another issue now on circleci.

**Comment by michaelbarton** [comment]
The relevant part of the error message on circleci appears to be here:

```
/dev/mapper/control: mknod failed: Operation not permitted
Failure to communicate with kernel device-mapper driver.
Check that device-mapper is available in the kernel.
Command failed
mount: permission denied
Could not mount /sys/kernel/security.
AppArmor detection and --privileged mode might break.
```

It looks like the privileged mode is not allowed on circleci. I will
contact them about this. We may have to consider a different solution.

**Comment by michaelbarton** [comment]
Did you open an issue on bioboxes or on dind?

**Comment by pbelmann** [comment]
@michaelbarton please update this issue if you get more information from circle ci.
Other options:
- switch to travis and try to run docker in docker with https://github.com/moul/travis-docker
- switch to jenkins. [It seems to work](https://github.com/tehranian/dind-jenkins-slave) (But then we need our own server)

**Comment by michaelbarton** [comment]
This pull request can merged now.

**Comment by michaelbarton** [comment]
I had to do several things to get this work.
- Docker-in-Docker will not work on circleci or any other CI server. The
  reason for this is that the `--privileged` flag is a security issue and
  allows the container to gain access to resource in the same way the sudo
  will. I think we should work to solve this somehow in future, I still
  however think we should provide the validator as a container as this seems
  to be the simplest way to do this. I am open to other suggestions though.
- I solved the problem on circleci by exporting the contents of `root` in the
  validation container and running the contents. This is quite messy as is
  becuase it litters the directory with files. We can tidy this up in future.
  This works because the circleci has a running docker daemon and this is
  used by the feature tests. The file `./script/test` will decide which set
  of tests to run depending on whether the CI variable is present in the
  environment. The docker-in-docker approach is still used if not on the CI
  server.
- The CI server still tests that the validator container builds.
- I removed the output-validator.py to simplify getting the tests working.
  Could we perhaps use the `validate-input` script with an output schema?
  This would work in tandem with the input schema for the short read
  assembler.
- The output directory should contain `biobox.yaml`. I think this file name
  is necessary to chain the containers together.

Please feel free to either merge this or continue to update the tests. I
suggest next we have a page on bioboxes.org outlining how the validator
container can be used to make sure a biobox assembler matches the spec.

**Comment by pbelmann** [comment]
yes I can integrate the validate-input binary later. I will update the rfc regarding  biobox.yaml.

**Pull request merged**
